// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package org.example.grpc;

/**
 * Protobuf type {@code services.DemoMessage}
 */
public  final class DemoMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.DemoMessage)
    DemoMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DemoMessage.newBuilder() to construct.
  private DemoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DemoMessage() {
    field1_ = "";
    field9_ = "";
    field18_ = "";
    field80_ = false;
    field81_ = false;
    field2_ = 0;
    field3_ = 0;
    field280_ = 0;
    field6_ = 0;
    field22_ = 0L;
    field4_ = "";
    field5_ = 0L;
    field59_ = false;
    field7_ = "";
    field16_ = 0;
    field130_ = 0;
    field12_ = false;
    field17_ = false;
    field13_ = false;
    field14_ = false;
    field104_ = 0;
    field100_ = 0;
    field101_ = 0;
    field102_ = "";
    field103_ = "";
    field29_ = 0;
    field30_ = false;
    field60_ = 0;
    field271_ = 0;
    field272_ = 0;
    field150_ = 0;
    field23_ = 0;
    field24_ = false;
    field25_ = 0;
    field78_ = false;
    field67_ = 0;
    field68_ = 0;
    field128_ = 0;
    field129_ = "";
    field131_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DemoMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    int mutable_bitField1_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            field1_ = s;
            break;
          }
          case 16: {

            field2_ = input.readInt32();
            break;
          }
          case 24: {

            field3_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            field4_ = s;
            break;
          }
          case 41: {

            field5_ = input.readFixed64();
            break;
          }
          case 48: {

            field6_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            field7_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            field9_ = s;
            break;
          }
          case 96: {

            field12_ = input.readBool();
            break;
          }
          case 104: {

            field13_ = input.readBool();
            break;
          }
          case 112: {

            field14_ = input.readBool();
            break;
          }
          case 128: {

            field16_ = input.readInt32();
            break;
          }
          case 136: {

            field17_ = input.readBool();
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            field18_ = s;
            break;
          }
          case 176: {

            field22_ = input.readInt64();
            break;
          }
          case 184: {

            field23_ = input.readInt32();
            break;
          }
          case 192: {

            field24_ = input.readBool();
            break;
          }
          case 200: {

            field25_ = input.readInt32();
            break;
          }
          case 232: {

            field29_ = input.readInt32();
            break;
          }
          case 240: {

            field30_ = input.readBool();
            break;
          }
          case 472: {

            field59_ = input.readBool();
            break;
          }
          case 480: {

            field60_ = input.readInt32();
            break;
          }
          case 536: {

            field67_ = input.readInt32();
            break;
          }
          case 544: {

            field68_ = input.readInt32();
            break;
          }
          case 624: {

            field78_ = input.readBool();
            break;
          }
          case 640: {

            field80_ = input.readBool();
            break;
          }
          case 648: {

            field81_ = input.readBool();
            break;
          }
          case 800: {

            field100_ = input.readInt32();
            break;
          }
          case 808: {

            field101_ = input.readInt32();
            break;
          }
          case 818: {
            java.lang.String s = input.readStringRequireUtf8();

            field102_ = s;
            break;
          }
          case 826: {
            java.lang.String s = input.readStringRequireUtf8();

            field103_ = s;
            break;
          }
          case 832: {

            field104_ = input.readInt32();
            break;
          }
          case 1024: {

            field128_ = input.readInt32();
            break;
          }
          case 1034: {
            java.lang.String s = input.readStringRequireUtf8();

            field129_ = s;
            break;
          }
          case 1040: {

            field130_ = input.readInt32();
            break;
          }
          case 1048: {

            field131_ = input.readInt32();
            break;
          }
          case 1200: {

            field150_ = input.readInt32();
            break;
          }
          case 2168: {

            field271_ = input.readInt32();
            break;
          }
          case 2176: {

            field272_ = input.readInt32();
            break;
          }
          case 2240: {

            field280_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.grpc.DemoProtos.internal_static_services_DemoMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.grpc.DemoProtos.internal_static_services_DemoMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.grpc.DemoMessage.class, org.example.grpc.DemoMessage.Builder.class);
  }

  public static final int FIELD1_FIELD_NUMBER = 1;
  private volatile java.lang.Object field1_;
  /**
   * <code>string field1 = 1;</code>
   */
  public java.lang.String getField1() {
    java.lang.Object ref = field1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field1_ = s;
      return s;
    }
  }
  /**
   * <code>string field1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getField1Bytes() {
    java.lang.Object ref = field1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD9_FIELD_NUMBER = 9;
  private volatile java.lang.Object field9_;
  /**
   * <code>string field9 = 9;</code>
   */
  public java.lang.String getField9() {
    java.lang.Object ref = field9_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field9_ = s;
      return s;
    }
  }
  /**
   * <code>string field9 = 9;</code>
   */
  public com.google.protobuf.ByteString
      getField9Bytes() {
    java.lang.Object ref = field9_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field9_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD18_FIELD_NUMBER = 18;
  private volatile java.lang.Object field18_;
  /**
   * <code>string field18 = 18;</code>
   */
  public java.lang.String getField18() {
    java.lang.Object ref = field18_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field18_ = s;
      return s;
    }
  }
  /**
   * <code>string field18 = 18;</code>
   */
  public com.google.protobuf.ByteString
      getField18Bytes() {
    java.lang.Object ref = field18_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field18_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD80_FIELD_NUMBER = 80;
  private boolean field80_;
  /**
   * <code>bool field80 = 80;</code>
   */
  public boolean getField80() {
    return field80_;
  }

  public static final int FIELD81_FIELD_NUMBER = 81;
  private boolean field81_;
  /**
   * <code>bool field81 = 81;</code>
   */
  public boolean getField81() {
    return field81_;
  }

  public static final int FIELD2_FIELD_NUMBER = 2;
  private int field2_;
  /**
   * <code>int32 field2 = 2;</code>
   */
  public int getField2() {
    return field2_;
  }

  public static final int FIELD3_FIELD_NUMBER = 3;
  private int field3_;
  /**
   * <code>int32 field3 = 3;</code>
   */
  public int getField3() {
    return field3_;
  }

  public static final int FIELD280_FIELD_NUMBER = 280;
  private int field280_;
  /**
   * <code>int32 field280 = 280;</code>
   */
  public int getField280() {
    return field280_;
  }

  public static final int FIELD6_FIELD_NUMBER = 6;
  private int field6_;
  /**
   * <code>int32 field6 = 6;</code>
   */
  public int getField6() {
    return field6_;
  }

  public static final int FIELD22_FIELD_NUMBER = 22;
  private long field22_;
  /**
   * <code>int64 field22 = 22;</code>
   */
  public long getField22() {
    return field22_;
  }

  public static final int FIELD4_FIELD_NUMBER = 4;
  private volatile java.lang.Object field4_;
  /**
   * <code>string field4 = 4;</code>
   */
  public java.lang.String getField4() {
    java.lang.Object ref = field4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field4_ = s;
      return s;
    }
  }
  /**
   * <code>string field4 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getField4Bytes() {
    java.lang.Object ref = field4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD5_FIELD_NUMBER = 5;
  private long field5_;
  /**
   * <code>fixed64 field5 = 5;</code>
   */
  public long getField5() {
    return field5_;
  }

  public static final int FIELD59_FIELD_NUMBER = 59;
  private boolean field59_;
  /**
   * <code>bool field59 = 59;</code>
   */
  public boolean getField59() {
    return field59_;
  }

  public static final int FIELD7_FIELD_NUMBER = 7;
  private volatile java.lang.Object field7_;
  /**
   * <code>string field7 = 7;</code>
   */
  public java.lang.String getField7() {
    java.lang.Object ref = field7_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field7_ = s;
      return s;
    }
  }
  /**
   * <code>string field7 = 7;</code>
   */
  public com.google.protobuf.ByteString
      getField7Bytes() {
    java.lang.Object ref = field7_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field7_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD16_FIELD_NUMBER = 16;
  private int field16_;
  /**
   * <code>int32 field16 = 16;</code>
   */
  public int getField16() {
    return field16_;
  }

  public static final int FIELD130_FIELD_NUMBER = 130;
  private int field130_;
  /**
   * <code>int32 field130 = 130;</code>
   */
  public int getField130() {
    return field130_;
  }

  public static final int FIELD12_FIELD_NUMBER = 12;
  private boolean field12_;
  /**
   * <code>bool field12 = 12;</code>
   */
  public boolean getField12() {
    return field12_;
  }

  public static final int FIELD17_FIELD_NUMBER = 17;
  private boolean field17_;
  /**
   * <code>bool field17 = 17;</code>
   */
  public boolean getField17() {
    return field17_;
  }

  public static final int FIELD13_FIELD_NUMBER = 13;
  private boolean field13_;
  /**
   * <code>bool field13 = 13;</code>
   */
  public boolean getField13() {
    return field13_;
  }

  public static final int FIELD14_FIELD_NUMBER = 14;
  private boolean field14_;
  /**
   * <code>bool field14 = 14;</code>
   */
  public boolean getField14() {
    return field14_;
  }

  public static final int FIELD104_FIELD_NUMBER = 104;
  private int field104_;
  /**
   * <code>int32 field104 = 104;</code>
   */
  public int getField104() {
    return field104_;
  }

  public static final int FIELD100_FIELD_NUMBER = 100;
  private int field100_;
  /**
   * <code>int32 field100 = 100;</code>
   */
  public int getField100() {
    return field100_;
  }

  public static final int FIELD101_FIELD_NUMBER = 101;
  private int field101_;
  /**
   * <code>int32 field101 = 101;</code>
   */
  public int getField101() {
    return field101_;
  }

  public static final int FIELD102_FIELD_NUMBER = 102;
  private volatile java.lang.Object field102_;
  /**
   * <code>string field102 = 102;</code>
   */
  public java.lang.String getField102() {
    java.lang.Object ref = field102_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field102_ = s;
      return s;
    }
  }
  /**
   * <code>string field102 = 102;</code>
   */
  public com.google.protobuf.ByteString
      getField102Bytes() {
    java.lang.Object ref = field102_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field102_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD103_FIELD_NUMBER = 103;
  private volatile java.lang.Object field103_;
  /**
   * <code>string field103 = 103;</code>
   */
  public java.lang.String getField103() {
    java.lang.Object ref = field103_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field103_ = s;
      return s;
    }
  }
  /**
   * <code>string field103 = 103;</code>
   */
  public com.google.protobuf.ByteString
      getField103Bytes() {
    java.lang.Object ref = field103_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field103_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD29_FIELD_NUMBER = 29;
  private int field29_;
  /**
   * <code>int32 field29 = 29;</code>
   */
  public int getField29() {
    return field29_;
  }

  public static final int FIELD30_FIELD_NUMBER = 30;
  private boolean field30_;
  /**
   * <code>bool field30 = 30;</code>
   */
  public boolean getField30() {
    return field30_;
  }

  public static final int FIELD60_FIELD_NUMBER = 60;
  private int field60_;
  /**
   * <code>int32 field60 = 60;</code>
   */
  public int getField60() {
    return field60_;
  }

  public static final int FIELD271_FIELD_NUMBER = 271;
  private int field271_;
  /**
   * <code>int32 field271 = 271;</code>
   */
  public int getField271() {
    return field271_;
  }

  public static final int FIELD272_FIELD_NUMBER = 272;
  private int field272_;
  /**
   * <code>int32 field272 = 272;</code>
   */
  public int getField272() {
    return field272_;
  }

  public static final int FIELD150_FIELD_NUMBER = 150;
  private int field150_;
  /**
   * <code>int32 field150 = 150;</code>
   */
  public int getField150() {
    return field150_;
  }

  public static final int FIELD23_FIELD_NUMBER = 23;
  private int field23_;
  /**
   * <code>int32 field23 = 23;</code>
   */
  public int getField23() {
    return field23_;
  }

  public static final int FIELD24_FIELD_NUMBER = 24;
  private boolean field24_;
  /**
   * <code>bool field24 = 24;</code>
   */
  public boolean getField24() {
    return field24_;
  }

  public static final int FIELD25_FIELD_NUMBER = 25;
  private int field25_;
  /**
   * <code>int32 field25 = 25;</code>
   */
  public int getField25() {
    return field25_;
  }

  public static final int FIELD78_FIELD_NUMBER = 78;
  private boolean field78_;
  /**
   * <code>bool field78 = 78;</code>
   */
  public boolean getField78() {
    return field78_;
  }

  public static final int FIELD67_FIELD_NUMBER = 67;
  private int field67_;
  /**
   * <code>int32 field67 = 67;</code>
   */
  public int getField67() {
    return field67_;
  }

  public static final int FIELD68_FIELD_NUMBER = 68;
  private int field68_;
  /**
   * <code>int32 field68 = 68;</code>
   */
  public int getField68() {
    return field68_;
  }

  public static final int FIELD128_FIELD_NUMBER = 128;
  private int field128_;
  /**
   * <code>int32 field128 = 128;</code>
   */
  public int getField128() {
    return field128_;
  }

  public static final int FIELD129_FIELD_NUMBER = 129;
  private volatile java.lang.Object field129_;
  /**
   * <code>string field129 = 129;</code>
   */
  public java.lang.String getField129() {
    java.lang.Object ref = field129_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field129_ = s;
      return s;
    }
  }
  /**
   * <code>string field129 = 129;</code>
   */
  public com.google.protobuf.ByteString
      getField129Bytes() {
    java.lang.Object ref = field129_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field129_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELD131_FIELD_NUMBER = 131;
  private int field131_;
  /**
   * <code>int32 field131 = 131;</code>
   */
  public int getField131() {
    return field131_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getField1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, field1_);
    }
    if (field2_ != 0) {
      output.writeInt32(2, field2_);
    }
    if (field3_ != 0) {
      output.writeInt32(3, field3_);
    }
    if (!getField4Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, field4_);
    }
    if (field5_ != 0L) {
      output.writeFixed64(5, field5_);
    }
    if (field6_ != 0) {
      output.writeInt32(6, field6_);
    }
    if (!getField7Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, field7_);
    }
    if (!getField9Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, field9_);
    }
    if (field12_ != false) {
      output.writeBool(12, field12_);
    }
    if (field13_ != false) {
      output.writeBool(13, field13_);
    }
    if (field14_ != false) {
      output.writeBool(14, field14_);
    }
    if (field16_ != 0) {
      output.writeInt32(16, field16_);
    }
    if (field17_ != false) {
      output.writeBool(17, field17_);
    }
    if (!getField18Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, field18_);
    }
    if (field22_ != 0L) {
      output.writeInt64(22, field22_);
    }
    if (field23_ != 0) {
      output.writeInt32(23, field23_);
    }
    if (field24_ != false) {
      output.writeBool(24, field24_);
    }
    if (field25_ != 0) {
      output.writeInt32(25, field25_);
    }
    if (field29_ != 0) {
      output.writeInt32(29, field29_);
    }
    if (field30_ != false) {
      output.writeBool(30, field30_);
    }
    if (field59_ != false) {
      output.writeBool(59, field59_);
    }
    if (field60_ != 0) {
      output.writeInt32(60, field60_);
    }
    if (field67_ != 0) {
      output.writeInt32(67, field67_);
    }
    if (field68_ != 0) {
      output.writeInt32(68, field68_);
    }
    if (field78_ != false) {
      output.writeBool(78, field78_);
    }
    if (field80_ != false) {
      output.writeBool(80, field80_);
    }
    if (field81_ != false) {
      output.writeBool(81, field81_);
    }
    if (field100_ != 0) {
      output.writeInt32(100, field100_);
    }
    if (field101_ != 0) {
      output.writeInt32(101, field101_);
    }
    if (!getField102Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 102, field102_);
    }
    if (!getField103Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 103, field103_);
    }
    if (field104_ != 0) {
      output.writeInt32(104, field104_);
    }
    if (field128_ != 0) {
      output.writeInt32(128, field128_);
    }
    if (!getField129Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 129, field129_);
    }
    if (field130_ != 0) {
      output.writeInt32(130, field130_);
    }
    if (field131_ != 0) {
      output.writeInt32(131, field131_);
    }
    if (field150_ != 0) {
      output.writeInt32(150, field150_);
    }
    if (field271_ != 0) {
      output.writeInt32(271, field271_);
    }
    if (field272_ != 0) {
      output.writeInt32(272, field272_);
    }
    if (field280_ != 0) {
      output.writeInt32(280, field280_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getField1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, field1_);
    }
    if (field2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, field2_);
    }
    if (field3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, field3_);
    }
    if (!getField4Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, field4_);
    }
    if (field5_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(5, field5_);
    }
    if (field6_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, field6_);
    }
    if (!getField7Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, field7_);
    }
    if (!getField9Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, field9_);
    }
    if (field12_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, field12_);
    }
    if (field13_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, field13_);
    }
    if (field14_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, field14_);
    }
    if (field16_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, field16_);
    }
    if (field17_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, field17_);
    }
    if (!getField18Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, field18_);
    }
    if (field22_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(22, field22_);
    }
    if (field23_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, field23_);
    }
    if (field24_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(24, field24_);
    }
    if (field25_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(25, field25_);
    }
    if (field29_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(29, field29_);
    }
    if (field30_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(30, field30_);
    }
    if (field59_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(59, field59_);
    }
    if (field60_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(60, field60_);
    }
    if (field67_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(67, field67_);
    }
    if (field68_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(68, field68_);
    }
    if (field78_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(78, field78_);
    }
    if (field80_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(80, field80_);
    }
    if (field81_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(81, field81_);
    }
    if (field100_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(100, field100_);
    }
    if (field101_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(101, field101_);
    }
    if (!getField102Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(102, field102_);
    }
    if (!getField103Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(103, field103_);
    }
    if (field104_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(104, field104_);
    }
    if (field128_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(128, field128_);
    }
    if (!getField129Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(129, field129_);
    }
    if (field130_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(130, field130_);
    }
    if (field131_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(131, field131_);
    }
    if (field150_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(150, field150_);
    }
    if (field271_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(271, field271_);
    }
    if (field272_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(272, field272_);
    }
    if (field280_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(280, field280_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.grpc.DemoMessage)) {
      return super.equals(obj);
    }
    org.example.grpc.DemoMessage other = (org.example.grpc.DemoMessage) obj;

    boolean result = true;
    result = result && getField1()
        .equals(other.getField1());
    result = result && getField9()
        .equals(other.getField9());
    result = result && getField18()
        .equals(other.getField18());
    result = result && (getField80()
        == other.getField80());
    result = result && (getField81()
        == other.getField81());
    result = result && (getField2()
        == other.getField2());
    result = result && (getField3()
        == other.getField3());
    result = result && (getField280()
        == other.getField280());
    result = result && (getField6()
        == other.getField6());
    result = result && (getField22()
        == other.getField22());
    result = result && getField4()
        .equals(other.getField4());
    result = result && (getField5()
        == other.getField5());
    result = result && (getField59()
        == other.getField59());
    result = result && getField7()
        .equals(other.getField7());
    result = result && (getField16()
        == other.getField16());
    result = result && (getField130()
        == other.getField130());
    result = result && (getField12()
        == other.getField12());
    result = result && (getField17()
        == other.getField17());
    result = result && (getField13()
        == other.getField13());
    result = result && (getField14()
        == other.getField14());
    result = result && (getField104()
        == other.getField104());
    result = result && (getField100()
        == other.getField100());
    result = result && (getField101()
        == other.getField101());
    result = result && getField102()
        .equals(other.getField102());
    result = result && getField103()
        .equals(other.getField103());
    result = result && (getField29()
        == other.getField29());
    result = result && (getField30()
        == other.getField30());
    result = result && (getField60()
        == other.getField60());
    result = result && (getField271()
        == other.getField271());
    result = result && (getField272()
        == other.getField272());
    result = result && (getField150()
        == other.getField150());
    result = result && (getField23()
        == other.getField23());
    result = result && (getField24()
        == other.getField24());
    result = result && (getField25()
        == other.getField25());
    result = result && (getField78()
        == other.getField78());
    result = result && (getField67()
        == other.getField67());
    result = result && (getField68()
        == other.getField68());
    result = result && (getField128()
        == other.getField128());
    result = result && getField129()
        .equals(other.getField129());
    result = result && (getField131()
        == other.getField131());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIELD1_FIELD_NUMBER;
    hash = (53 * hash) + getField1().hashCode();
    hash = (37 * hash) + FIELD9_FIELD_NUMBER;
    hash = (53 * hash) + getField9().hashCode();
    hash = (37 * hash) + FIELD18_FIELD_NUMBER;
    hash = (53 * hash) + getField18().hashCode();
    hash = (37 * hash) + FIELD80_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField80());
    hash = (37 * hash) + FIELD81_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField81());
    hash = (37 * hash) + FIELD2_FIELD_NUMBER;
    hash = (53 * hash) + getField2();
    hash = (37 * hash) + FIELD3_FIELD_NUMBER;
    hash = (53 * hash) + getField3();
    hash = (37 * hash) + FIELD280_FIELD_NUMBER;
    hash = (53 * hash) + getField280();
    hash = (37 * hash) + FIELD6_FIELD_NUMBER;
    hash = (53 * hash) + getField6();
    hash = (37 * hash) + FIELD22_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getField22());
    hash = (37 * hash) + FIELD4_FIELD_NUMBER;
    hash = (53 * hash) + getField4().hashCode();
    hash = (37 * hash) + FIELD5_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getField5());
    hash = (37 * hash) + FIELD59_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField59());
    hash = (37 * hash) + FIELD7_FIELD_NUMBER;
    hash = (53 * hash) + getField7().hashCode();
    hash = (37 * hash) + FIELD16_FIELD_NUMBER;
    hash = (53 * hash) + getField16();
    hash = (37 * hash) + FIELD130_FIELD_NUMBER;
    hash = (53 * hash) + getField130();
    hash = (37 * hash) + FIELD12_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField12());
    hash = (37 * hash) + FIELD17_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField17());
    hash = (37 * hash) + FIELD13_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField13());
    hash = (37 * hash) + FIELD14_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField14());
    hash = (37 * hash) + FIELD104_FIELD_NUMBER;
    hash = (53 * hash) + getField104();
    hash = (37 * hash) + FIELD100_FIELD_NUMBER;
    hash = (53 * hash) + getField100();
    hash = (37 * hash) + FIELD101_FIELD_NUMBER;
    hash = (53 * hash) + getField101();
    hash = (37 * hash) + FIELD102_FIELD_NUMBER;
    hash = (53 * hash) + getField102().hashCode();
    hash = (37 * hash) + FIELD103_FIELD_NUMBER;
    hash = (53 * hash) + getField103().hashCode();
    hash = (37 * hash) + FIELD29_FIELD_NUMBER;
    hash = (53 * hash) + getField29();
    hash = (37 * hash) + FIELD30_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField30());
    hash = (37 * hash) + FIELD60_FIELD_NUMBER;
    hash = (53 * hash) + getField60();
    hash = (37 * hash) + FIELD271_FIELD_NUMBER;
    hash = (53 * hash) + getField271();
    hash = (37 * hash) + FIELD272_FIELD_NUMBER;
    hash = (53 * hash) + getField272();
    hash = (37 * hash) + FIELD150_FIELD_NUMBER;
    hash = (53 * hash) + getField150();
    hash = (37 * hash) + FIELD23_FIELD_NUMBER;
    hash = (53 * hash) + getField23();
    hash = (37 * hash) + FIELD24_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField24());
    hash = (37 * hash) + FIELD25_FIELD_NUMBER;
    hash = (53 * hash) + getField25();
    hash = (37 * hash) + FIELD78_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getField78());
    hash = (37 * hash) + FIELD67_FIELD_NUMBER;
    hash = (53 * hash) + getField67();
    hash = (37 * hash) + FIELD68_FIELD_NUMBER;
    hash = (53 * hash) + getField68();
    hash = (37 * hash) + FIELD128_FIELD_NUMBER;
    hash = (53 * hash) + getField128();
    hash = (37 * hash) + FIELD129_FIELD_NUMBER;
    hash = (53 * hash) + getField129().hashCode();
    hash = (37 * hash) + FIELD131_FIELD_NUMBER;
    hash = (53 * hash) + getField131();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.grpc.DemoMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.grpc.DemoMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.grpc.DemoMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.grpc.DemoMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.grpc.DemoMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.grpc.DemoMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.grpc.DemoMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.grpc.DemoMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.grpc.DemoMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.grpc.DemoMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.grpc.DemoMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.grpc.DemoMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.grpc.DemoMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.DemoMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.DemoMessage)
      org.example.grpc.DemoMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.DemoProtos.internal_static_services_DemoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.DemoProtos.internal_static_services_DemoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.DemoMessage.class, org.example.grpc.DemoMessage.Builder.class);
    }

    // Construct using org.example.grpc.DemoMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      field1_ = "";

      field9_ = "";

      field18_ = "";

      field80_ = false;

      field81_ = false;

      field2_ = 0;

      field3_ = 0;

      field280_ = 0;

      field6_ = 0;

      field22_ = 0L;

      field4_ = "";

      field5_ = 0L;

      field59_ = false;

      field7_ = "";

      field16_ = 0;

      field130_ = 0;

      field12_ = false;

      field17_ = false;

      field13_ = false;

      field14_ = false;

      field104_ = 0;

      field100_ = 0;

      field101_ = 0;

      field102_ = "";

      field103_ = "";

      field29_ = 0;

      field30_ = false;

      field60_ = 0;

      field271_ = 0;

      field272_ = 0;

      field150_ = 0;

      field23_ = 0;

      field24_ = false;

      field25_ = 0;

      field78_ = false;

      field67_ = 0;

      field68_ = 0;

      field128_ = 0;

      field129_ = "";

      field131_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.grpc.DemoProtos.internal_static_services_DemoMessage_descriptor;
    }

    public org.example.grpc.DemoMessage getDefaultInstanceForType() {
      return org.example.grpc.DemoMessage.getDefaultInstance();
    }

    public org.example.grpc.DemoMessage build() {
      org.example.grpc.DemoMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.example.grpc.DemoMessage buildPartial() {
      org.example.grpc.DemoMessage result = new org.example.grpc.DemoMessage(this);
      result.field1_ = field1_;
      result.field9_ = field9_;
      result.field18_ = field18_;
      result.field80_ = field80_;
      result.field81_ = field81_;
      result.field2_ = field2_;
      result.field3_ = field3_;
      result.field280_ = field280_;
      result.field6_ = field6_;
      result.field22_ = field22_;
      result.field4_ = field4_;
      result.field5_ = field5_;
      result.field59_ = field59_;
      result.field7_ = field7_;
      result.field16_ = field16_;
      result.field130_ = field130_;
      result.field12_ = field12_;
      result.field17_ = field17_;
      result.field13_ = field13_;
      result.field14_ = field14_;
      result.field104_ = field104_;
      result.field100_ = field100_;
      result.field101_ = field101_;
      result.field102_ = field102_;
      result.field103_ = field103_;
      result.field29_ = field29_;
      result.field30_ = field30_;
      result.field60_ = field60_;
      result.field271_ = field271_;
      result.field272_ = field272_;
      result.field150_ = field150_;
      result.field23_ = field23_;
      result.field24_ = field24_;
      result.field25_ = field25_;
      result.field78_ = field78_;
      result.field67_ = field67_;
      result.field68_ = field68_;
      result.field128_ = field128_;
      result.field129_ = field129_;
      result.field131_ = field131_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.grpc.DemoMessage) {
        return mergeFrom((org.example.grpc.DemoMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.grpc.DemoMessage other) {
      if (other == org.example.grpc.DemoMessage.getDefaultInstance()) return this;
      if (!other.getField1().isEmpty()) {
        field1_ = other.field1_;
        onChanged();
      }
      if (!other.getField9().isEmpty()) {
        field9_ = other.field9_;
        onChanged();
      }
      if (!other.getField18().isEmpty()) {
        field18_ = other.field18_;
        onChanged();
      }
      if (other.getField80() != false) {
        setField80(other.getField80());
      }
      if (other.getField81() != false) {
        setField81(other.getField81());
      }
      if (other.getField2() != 0) {
        setField2(other.getField2());
      }
      if (other.getField3() != 0) {
        setField3(other.getField3());
      }
      if (other.getField280() != 0) {
        setField280(other.getField280());
      }
      if (other.getField6() != 0) {
        setField6(other.getField6());
      }
      if (other.getField22() != 0L) {
        setField22(other.getField22());
      }
      if (!other.getField4().isEmpty()) {
        field4_ = other.field4_;
        onChanged();
      }
      if (other.getField5() != 0L) {
        setField5(other.getField5());
      }
      if (other.getField59() != false) {
        setField59(other.getField59());
      }
      if (!other.getField7().isEmpty()) {
        field7_ = other.field7_;
        onChanged();
      }
      if (other.getField16() != 0) {
        setField16(other.getField16());
      }
      if (other.getField130() != 0) {
        setField130(other.getField130());
      }
      if (other.getField12() != false) {
        setField12(other.getField12());
      }
      if (other.getField17() != false) {
        setField17(other.getField17());
      }
      if (other.getField13() != false) {
        setField13(other.getField13());
      }
      if (other.getField14() != false) {
        setField14(other.getField14());
      }
      if (other.getField104() != 0) {
        setField104(other.getField104());
      }
      if (other.getField100() != 0) {
        setField100(other.getField100());
      }
      if (other.getField101() != 0) {
        setField101(other.getField101());
      }
      if (!other.getField102().isEmpty()) {
        field102_ = other.field102_;
        onChanged();
      }
      if (!other.getField103().isEmpty()) {
        field103_ = other.field103_;
        onChanged();
      }
      if (other.getField29() != 0) {
        setField29(other.getField29());
      }
      if (other.getField30() != false) {
        setField30(other.getField30());
      }
      if (other.getField60() != 0) {
        setField60(other.getField60());
      }
      if (other.getField271() != 0) {
        setField271(other.getField271());
      }
      if (other.getField272() != 0) {
        setField272(other.getField272());
      }
      if (other.getField150() != 0) {
        setField150(other.getField150());
      }
      if (other.getField23() != 0) {
        setField23(other.getField23());
      }
      if (other.getField24() != false) {
        setField24(other.getField24());
      }
      if (other.getField25() != 0) {
        setField25(other.getField25());
      }
      if (other.getField78() != false) {
        setField78(other.getField78());
      }
      if (other.getField67() != 0) {
        setField67(other.getField67());
      }
      if (other.getField68() != 0) {
        setField68(other.getField68());
      }
      if (other.getField128() != 0) {
        setField128(other.getField128());
      }
      if (!other.getField129().isEmpty()) {
        field129_ = other.field129_;
        onChanged();
      }
      if (other.getField131() != 0) {
        setField131(other.getField131());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.grpc.DemoMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.grpc.DemoMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object field1_ = "";
    /**
     * <code>string field1 = 1;</code>
     */
    public java.lang.String getField1() {
      java.lang.Object ref = field1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getField1Bytes() {
      java.lang.Object ref = field1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field1 = 1;</code>
     */
    public Builder setField1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field1 = 1;</code>
     */
    public Builder clearField1() {
      
      field1_ = getDefaultInstance().getField1();
      onChanged();
      return this;
    }
    /**
     * <code>string field1 = 1;</code>
     */
    public Builder setField1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object field9_ = "";
    /**
     * <code>string field9 = 9;</code>
     */
    public java.lang.String getField9() {
      java.lang.Object ref = field9_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field9_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field9 = 9;</code>
     */
    public com.google.protobuf.ByteString
        getField9Bytes() {
      java.lang.Object ref = field9_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field9_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field9 = 9;</code>
     */
    public Builder setField9(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field9_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field9 = 9;</code>
     */
    public Builder clearField9() {
      
      field9_ = getDefaultInstance().getField9();
      onChanged();
      return this;
    }
    /**
     * <code>string field9 = 9;</code>
     */
    public Builder setField9Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field9_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object field18_ = "";
    /**
     * <code>string field18 = 18;</code>
     */
    public java.lang.String getField18() {
      java.lang.Object ref = field18_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field18_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public com.google.protobuf.ByteString
        getField18Bytes() {
      java.lang.Object ref = field18_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field18_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public Builder setField18(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field18_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public Builder clearField18() {
      
      field18_ = getDefaultInstance().getField18();
      onChanged();
      return this;
    }
    /**
     * <code>string field18 = 18;</code>
     */
    public Builder setField18Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field18_ = value;
      onChanged();
      return this;
    }

    private boolean field80_ ;
    /**
     * <code>bool field80 = 80;</code>
     */
    public boolean getField80() {
      return field80_;
    }
    /**
     * <code>bool field80 = 80;</code>
     */
    public Builder setField80(boolean value) {
      
      field80_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field80 = 80;</code>
     */
    public Builder clearField80() {
      
      field80_ = false;
      onChanged();
      return this;
    }

    private boolean field81_ ;
    /**
     * <code>bool field81 = 81;</code>
     */
    public boolean getField81() {
      return field81_;
    }
    /**
     * <code>bool field81 = 81;</code>
     */
    public Builder setField81(boolean value) {
      
      field81_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field81 = 81;</code>
     */
    public Builder clearField81() {
      
      field81_ = false;
      onChanged();
      return this;
    }

    private int field2_ ;
    /**
     * <code>int32 field2 = 2;</code>
     */
    public int getField2() {
      return field2_;
    }
    /**
     * <code>int32 field2 = 2;</code>
     */
    public Builder setField2(int value) {
      
      field2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field2 = 2;</code>
     */
    public Builder clearField2() {
      
      field2_ = 0;
      onChanged();
      return this;
    }

    private int field3_ ;
    /**
     * <code>int32 field3 = 3;</code>
     */
    public int getField3() {
      return field3_;
    }
    /**
     * <code>int32 field3 = 3;</code>
     */
    public Builder setField3(int value) {
      
      field3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field3 = 3;</code>
     */
    public Builder clearField3() {
      
      field3_ = 0;
      onChanged();
      return this;
    }

    private int field280_ ;
    /**
     * <code>int32 field280 = 280;</code>
     */
    public int getField280() {
      return field280_;
    }
    /**
     * <code>int32 field280 = 280;</code>
     */
    public Builder setField280(int value) {
      
      field280_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field280 = 280;</code>
     */
    public Builder clearField280() {
      
      field280_ = 0;
      onChanged();
      return this;
    }

    private int field6_ ;
    /**
     * <code>int32 field6 = 6;</code>
     */
    public int getField6() {
      return field6_;
    }
    /**
     * <code>int32 field6 = 6;</code>
     */
    public Builder setField6(int value) {
      
      field6_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field6 = 6;</code>
     */
    public Builder clearField6() {
      
      field6_ = 0;
      onChanged();
      return this;
    }

    private long field22_ ;
    /**
     * <code>int64 field22 = 22;</code>
     */
    public long getField22() {
      return field22_;
    }
    /**
     * <code>int64 field22 = 22;</code>
     */
    public Builder setField22(long value) {
      
      field22_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 field22 = 22;</code>
     */
    public Builder clearField22() {
      
      field22_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object field4_ = "";
    /**
     * <code>string field4 = 4;</code>
     */
    public java.lang.String getField4() {
      java.lang.Object ref = field4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getField4Bytes() {
      java.lang.Object ref = field4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public Builder setField4(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public Builder clearField4() {
      
      field4_ = getDefaultInstance().getField4();
      onChanged();
      return this;
    }
    /**
     * <code>string field4 = 4;</code>
     */
    public Builder setField4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field4_ = value;
      onChanged();
      return this;
    }

    private long field5_ ;
    /**
     * <code>fixed64 field5 = 5;</code>
     */
    public long getField5() {
      return field5_;
    }
    /**
     * <code>fixed64 field5 = 5;</code>
     */
    public Builder setField5(long value) {
      
      field5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 field5 = 5;</code>
     */
    public Builder clearField5() {
      
      field5_ = 0L;
      onChanged();
      return this;
    }

    private boolean field59_ ;
    /**
     * <code>bool field59 = 59;</code>
     */
    public boolean getField59() {
      return field59_;
    }
    /**
     * <code>bool field59 = 59;</code>
     */
    public Builder setField59(boolean value) {
      
      field59_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field59 = 59;</code>
     */
    public Builder clearField59() {
      
      field59_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object field7_ = "";
    /**
     * <code>string field7 = 7;</code>
     */
    public java.lang.String getField7() {
      java.lang.Object ref = field7_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field7_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field7 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getField7Bytes() {
      java.lang.Object ref = field7_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field7_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field7 = 7;</code>
     */
    public Builder setField7(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field7_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field7 = 7;</code>
     */
    public Builder clearField7() {
      
      field7_ = getDefaultInstance().getField7();
      onChanged();
      return this;
    }
    /**
     * <code>string field7 = 7;</code>
     */
    public Builder setField7Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field7_ = value;
      onChanged();
      return this;
    }

    private int field16_ ;
    /**
     * <code>int32 field16 = 16;</code>
     */
    public int getField16() {
      return field16_;
    }
    /**
     * <code>int32 field16 = 16;</code>
     */
    public Builder setField16(int value) {
      
      field16_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field16 = 16;</code>
     */
    public Builder clearField16() {
      
      field16_ = 0;
      onChanged();
      return this;
    }

    private int field130_ ;
    /**
     * <code>int32 field130 = 130;</code>
     */
    public int getField130() {
      return field130_;
    }
    /**
     * <code>int32 field130 = 130;</code>
     */
    public Builder setField130(int value) {
      
      field130_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field130 = 130;</code>
     */
    public Builder clearField130() {
      
      field130_ = 0;
      onChanged();
      return this;
    }

    private boolean field12_ ;
    /**
     * <code>bool field12 = 12;</code>
     */
    public boolean getField12() {
      return field12_;
    }
    /**
     * <code>bool field12 = 12;</code>
     */
    public Builder setField12(boolean value) {
      
      field12_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field12 = 12;</code>
     */
    public Builder clearField12() {
      
      field12_ = false;
      onChanged();
      return this;
    }

    private boolean field17_ ;
    /**
     * <code>bool field17 = 17;</code>
     */
    public boolean getField17() {
      return field17_;
    }
    /**
     * <code>bool field17 = 17;</code>
     */
    public Builder setField17(boolean value) {
      
      field17_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field17 = 17;</code>
     */
    public Builder clearField17() {
      
      field17_ = false;
      onChanged();
      return this;
    }

    private boolean field13_ ;
    /**
     * <code>bool field13 = 13;</code>
     */
    public boolean getField13() {
      return field13_;
    }
    /**
     * <code>bool field13 = 13;</code>
     */
    public Builder setField13(boolean value) {
      
      field13_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field13 = 13;</code>
     */
    public Builder clearField13() {
      
      field13_ = false;
      onChanged();
      return this;
    }

    private boolean field14_ ;
    /**
     * <code>bool field14 = 14;</code>
     */
    public boolean getField14() {
      return field14_;
    }
    /**
     * <code>bool field14 = 14;</code>
     */
    public Builder setField14(boolean value) {
      
      field14_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field14 = 14;</code>
     */
    public Builder clearField14() {
      
      field14_ = false;
      onChanged();
      return this;
    }

    private int field104_ ;
    /**
     * <code>int32 field104 = 104;</code>
     */
    public int getField104() {
      return field104_;
    }
    /**
     * <code>int32 field104 = 104;</code>
     */
    public Builder setField104(int value) {
      
      field104_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field104 = 104;</code>
     */
    public Builder clearField104() {
      
      field104_ = 0;
      onChanged();
      return this;
    }

    private int field100_ ;
    /**
     * <code>int32 field100 = 100;</code>
     */
    public int getField100() {
      return field100_;
    }
    /**
     * <code>int32 field100 = 100;</code>
     */
    public Builder setField100(int value) {
      
      field100_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field100 = 100;</code>
     */
    public Builder clearField100() {
      
      field100_ = 0;
      onChanged();
      return this;
    }

    private int field101_ ;
    /**
     * <code>int32 field101 = 101;</code>
     */
    public int getField101() {
      return field101_;
    }
    /**
     * <code>int32 field101 = 101;</code>
     */
    public Builder setField101(int value) {
      
      field101_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field101 = 101;</code>
     */
    public Builder clearField101() {
      
      field101_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field102_ = "";
    /**
     * <code>string field102 = 102;</code>
     */
    public java.lang.String getField102() {
      java.lang.Object ref = field102_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field102_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field102 = 102;</code>
     */
    public com.google.protobuf.ByteString
        getField102Bytes() {
      java.lang.Object ref = field102_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field102_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field102 = 102;</code>
     */
    public Builder setField102(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field102_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field102 = 102;</code>
     */
    public Builder clearField102() {
      
      field102_ = getDefaultInstance().getField102();
      onChanged();
      return this;
    }
    /**
     * <code>string field102 = 102;</code>
     */
    public Builder setField102Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field102_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object field103_ = "";
    /**
     * <code>string field103 = 103;</code>
     */
    public java.lang.String getField103() {
      java.lang.Object ref = field103_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field103_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field103 = 103;</code>
     */
    public com.google.protobuf.ByteString
        getField103Bytes() {
      java.lang.Object ref = field103_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field103_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field103 = 103;</code>
     */
    public Builder setField103(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field103_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field103 = 103;</code>
     */
    public Builder clearField103() {
      
      field103_ = getDefaultInstance().getField103();
      onChanged();
      return this;
    }
    /**
     * <code>string field103 = 103;</code>
     */
    public Builder setField103Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field103_ = value;
      onChanged();
      return this;
    }

    private int field29_ ;
    /**
     * <code>int32 field29 = 29;</code>
     */
    public int getField29() {
      return field29_;
    }
    /**
     * <code>int32 field29 = 29;</code>
     */
    public Builder setField29(int value) {
      
      field29_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field29 = 29;</code>
     */
    public Builder clearField29() {
      
      field29_ = 0;
      onChanged();
      return this;
    }

    private boolean field30_ ;
    /**
     * <code>bool field30 = 30;</code>
     */
    public boolean getField30() {
      return field30_;
    }
    /**
     * <code>bool field30 = 30;</code>
     */
    public Builder setField30(boolean value) {
      
      field30_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field30 = 30;</code>
     */
    public Builder clearField30() {
      
      field30_ = false;
      onChanged();
      return this;
    }

    private int field60_ ;
    /**
     * <code>int32 field60 = 60;</code>
     */
    public int getField60() {
      return field60_;
    }
    /**
     * <code>int32 field60 = 60;</code>
     */
    public Builder setField60(int value) {
      
      field60_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field60 = 60;</code>
     */
    public Builder clearField60() {
      
      field60_ = 0;
      onChanged();
      return this;
    }

    private int field271_ ;
    /**
     * <code>int32 field271 = 271;</code>
     */
    public int getField271() {
      return field271_;
    }
    /**
     * <code>int32 field271 = 271;</code>
     */
    public Builder setField271(int value) {
      
      field271_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field271 = 271;</code>
     */
    public Builder clearField271() {
      
      field271_ = 0;
      onChanged();
      return this;
    }

    private int field272_ ;
    /**
     * <code>int32 field272 = 272;</code>
     */
    public int getField272() {
      return field272_;
    }
    /**
     * <code>int32 field272 = 272;</code>
     */
    public Builder setField272(int value) {
      
      field272_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field272 = 272;</code>
     */
    public Builder clearField272() {
      
      field272_ = 0;
      onChanged();
      return this;
    }

    private int field150_ ;
    /**
     * <code>int32 field150 = 150;</code>
     */
    public int getField150() {
      return field150_;
    }
    /**
     * <code>int32 field150 = 150;</code>
     */
    public Builder setField150(int value) {
      
      field150_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field150 = 150;</code>
     */
    public Builder clearField150() {
      
      field150_ = 0;
      onChanged();
      return this;
    }

    private int field23_ ;
    /**
     * <code>int32 field23 = 23;</code>
     */
    public int getField23() {
      return field23_;
    }
    /**
     * <code>int32 field23 = 23;</code>
     */
    public Builder setField23(int value) {
      
      field23_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field23 = 23;</code>
     */
    public Builder clearField23() {
      
      field23_ = 0;
      onChanged();
      return this;
    }

    private boolean field24_ ;
    /**
     * <code>bool field24 = 24;</code>
     */
    public boolean getField24() {
      return field24_;
    }
    /**
     * <code>bool field24 = 24;</code>
     */
    public Builder setField24(boolean value) {
      
      field24_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field24 = 24;</code>
     */
    public Builder clearField24() {
      
      field24_ = false;
      onChanged();
      return this;
    }

    private int field25_ ;
    /**
     * <code>int32 field25 = 25;</code>
     */
    public int getField25() {
      return field25_;
    }
    /**
     * <code>int32 field25 = 25;</code>
     */
    public Builder setField25(int value) {
      
      field25_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field25 = 25;</code>
     */
    public Builder clearField25() {
      
      field25_ = 0;
      onChanged();
      return this;
    }

    private boolean field78_ ;
    /**
     * <code>bool field78 = 78;</code>
     */
    public boolean getField78() {
      return field78_;
    }
    /**
     * <code>bool field78 = 78;</code>
     */
    public Builder setField78(boolean value) {
      
      field78_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool field78 = 78;</code>
     */
    public Builder clearField78() {
      
      field78_ = false;
      onChanged();
      return this;
    }

    private int field67_ ;
    /**
     * <code>int32 field67 = 67;</code>
     */
    public int getField67() {
      return field67_;
    }
    /**
     * <code>int32 field67 = 67;</code>
     */
    public Builder setField67(int value) {
      
      field67_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field67 = 67;</code>
     */
    public Builder clearField67() {
      
      field67_ = 0;
      onChanged();
      return this;
    }

    private int field68_ ;
    /**
     * <code>int32 field68 = 68;</code>
     */
    public int getField68() {
      return field68_;
    }
    /**
     * <code>int32 field68 = 68;</code>
     */
    public Builder setField68(int value) {
      
      field68_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field68 = 68;</code>
     */
    public Builder clearField68() {
      
      field68_ = 0;
      onChanged();
      return this;
    }

    private int field128_ ;
    /**
     * <code>int32 field128 = 128;</code>
     */
    public int getField128() {
      return field128_;
    }
    /**
     * <code>int32 field128 = 128;</code>
     */
    public Builder setField128(int value) {
      
      field128_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field128 = 128;</code>
     */
    public Builder clearField128() {
      
      field128_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object field129_ = "";
    /**
     * <code>string field129 = 129;</code>
     */
    public java.lang.String getField129() {
      java.lang.Object ref = field129_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field129_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field129 = 129;</code>
     */
    public com.google.protobuf.ByteString
        getField129Bytes() {
      java.lang.Object ref = field129_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field129_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field129 = 129;</code>
     */
    public Builder setField129(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field129_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field129 = 129;</code>
     */
    public Builder clearField129() {
      
      field129_ = getDefaultInstance().getField129();
      onChanged();
      return this;
    }
    /**
     * <code>string field129 = 129;</code>
     */
    public Builder setField129Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field129_ = value;
      onChanged();
      return this;
    }

    private int field131_ ;
    /**
     * <code>int32 field131 = 131;</code>
     */
    public int getField131() {
      return field131_;
    }
    /**
     * <code>int32 field131 = 131;</code>
     */
    public Builder setField131(int value) {
      
      field131_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 field131 = 131;</code>
     */
    public Builder clearField131() {
      
      field131_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.DemoMessage)
  }

  // @@protoc_insertion_point(class_scope:services.DemoMessage)
  private static final org.example.grpc.DemoMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.grpc.DemoMessage();
  }

  public static org.example.grpc.DemoMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DemoMessage>
      PARSER = new com.google.protobuf.AbstractParser<DemoMessage>() {
    public DemoMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DemoMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DemoMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DemoMessage> getParserForType() {
    return PARSER;
  }

  public org.example.grpc.DemoMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

