// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package org.example.grpc;

public interface DemoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.DemoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field1 = 1;</code>
   */
  java.lang.String getField1();
  /**
   * <code>string field1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getField1Bytes();

  /**
   * <code>string field9 = 9;</code>
   */
  java.lang.String getField9();
  /**
   * <code>string field9 = 9;</code>
   */
  com.google.protobuf.ByteString
      getField9Bytes();

  /**
   * <code>string field18 = 18;</code>
   */
  java.lang.String getField18();
  /**
   * <code>string field18 = 18;</code>
   */
  com.google.protobuf.ByteString
      getField18Bytes();

  /**
   * <code>bool field80 = 80;</code>
   */
  boolean getField80();

  /**
   * <code>bool field81 = 81;</code>
   */
  boolean getField81();

  /**
   * <code>int32 field2 = 2;</code>
   */
  int getField2();

  /**
   * <code>int32 field3 = 3;</code>
   */
  int getField3();

  /**
   * <code>int32 field280 = 280;</code>
   */
  int getField280();

  /**
   * <code>int32 field6 = 6;</code>
   */
  int getField6();

  /**
   * <code>int64 field22 = 22;</code>
   */
  long getField22();

  /**
   * <code>string field4 = 4;</code>
   */
  java.lang.String getField4();
  /**
   * <code>string field4 = 4;</code>
   */
  com.google.protobuf.ByteString
      getField4Bytes();

  /**
   * <code>fixed64 field5 = 5;</code>
   */
  long getField5();

  /**
   * <code>bool field59 = 59;</code>
   */
  boolean getField59();

  /**
   * <code>string field7 = 7;</code>
   */
  java.lang.String getField7();
  /**
   * <code>string field7 = 7;</code>
   */
  com.google.protobuf.ByteString
      getField7Bytes();

  /**
   * <code>int32 field16 = 16;</code>
   */
  int getField16();

  /**
   * <code>int32 field130 = 130;</code>
   */
  int getField130();

  /**
   * <code>bool field12 = 12;</code>
   */
  boolean getField12();

  /**
   * <code>bool field17 = 17;</code>
   */
  boolean getField17();

  /**
   * <code>bool field13 = 13;</code>
   */
  boolean getField13();

  /**
   * <code>bool field14 = 14;</code>
   */
  boolean getField14();

  /**
   * <code>int32 field104 = 104;</code>
   */
  int getField104();

  /**
   * <code>int32 field100 = 100;</code>
   */
  int getField100();

  /**
   * <code>int32 field101 = 101;</code>
   */
  int getField101();

  /**
   * <code>string field102 = 102;</code>
   */
  java.lang.String getField102();
  /**
   * <code>string field102 = 102;</code>
   */
  com.google.protobuf.ByteString
      getField102Bytes();

  /**
   * <code>string field103 = 103;</code>
   */
  java.lang.String getField103();
  /**
   * <code>string field103 = 103;</code>
   */
  com.google.protobuf.ByteString
      getField103Bytes();

  /**
   * <code>int32 field29 = 29;</code>
   */
  int getField29();

  /**
   * <code>bool field30 = 30;</code>
   */
  boolean getField30();

  /**
   * <code>int32 field60 = 60;</code>
   */
  int getField60();

  /**
   * <code>int32 field271 = 271;</code>
   */
  int getField271();

  /**
   * <code>int32 field272 = 272;</code>
   */
  int getField272();

  /**
   * <code>int32 field150 = 150;</code>
   */
  int getField150();

  /**
   * <code>int32 field23 = 23;</code>
   */
  int getField23();

  /**
   * <code>bool field24 = 24;</code>
   */
  boolean getField24();

  /**
   * <code>int32 field25 = 25;</code>
   */
  int getField25();

  /**
   * <code>bool field78 = 78;</code>
   */
  boolean getField78();

  /**
   * <code>int32 field67 = 67;</code>
   */
  int getField67();

  /**
   * <code>int32 field68 = 68;</code>
   */
  int getField68();

  /**
   * <code>int32 field128 = 128;</code>
   */
  int getField128();

  /**
   * <code>string field129 = 129;</code>
   */
  java.lang.String getField129();
  /**
   * <code>string field129 = 129;</code>
   */
  com.google.protobuf.ByteString
      getField129Bytes();

  /**
   * <code>int32 field131 = 131;</code>
   */
  int getField131();
}
