// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package org.example.grpc;

public final class DemoProtos {
  private DemoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_DemoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_DemoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDemo.proto\022\010services\"\302\005\n\013DemoMessage\022\016" +
      "\n\006field1\030\001 \001(\t\022\016\n\006field9\030\t \001(\t\022\017\n\007field1" +
      "8\030\022 \001(\t\022\017\n\007field80\030P \001(\010\022\017\n\007field81\030Q \001(" +
      "\010\022\016\n\006field2\030\002 \001(\005\022\016\n\006field3\030\003 \001(\005\022\021\n\010fie" +
      "ld280\030\230\002 \001(\005\022\016\n\006field6\030\006 \001(\005\022\017\n\007field22\030" +
      "\026 \001(\003\022\016\n\006field4\030\004 \001(\t\022\016\n\006field5\030\005 \001(\006\022\017\n" +
      "\007field59\030; \001(\010\022\016\n\006field7\030\007 \001(\t\022\017\n\007field1" +
      "6\030\020 \001(\005\022\021\n\010field130\030\202\001 \001(\005\022\017\n\007field12\030\014 " +
      "\001(\010\022\017\n\007field17\030\021 \001(\010\022\017\n\007field13\030\r \001(\010\022\017\n" +
      "\007field14\030\016 \001(\010\022\020\n\010field104\030h \001(\005\022\020\n\010fiel" +
      "d100\030d \001(\005\022\020\n\010field101\030e \001(\005\022\020\n\010field102" +
      "\030f \001(\t\022\020\n\010field103\030g \001(\t\022\017\n\007field29\030\035 \001(" +
      "\005\022\017\n\007field30\030\036 \001(\010\022\017\n\007field60\030< \001(\005\022\021\n\010f" +
      "ield271\030\217\002 \001(\005\022\021\n\010field272\030\220\002 \001(\005\022\021\n\010fie" +
      "ld150\030\226\001 \001(\005\022\017\n\007field23\030\027 \001(\005\022\017\n\007field24" +
      "\030\030 \001(\010\022\017\n\007field25\030\031 \001(\005\022\017\n\007field78\030N \001(\010" +
      "\022\017\n\007field67\030C \001(\005\022\017\n\007field68\030D \001(\005\022\021\n\010fi" +
      "eld128\030\200\001 \001(\005\022\021\n\010field129\030\201\001 \001(\t\022\021\n\010fiel" +
      "d131\030\203\001 \001(\0052E\n\013DemoService\0226\n\004demo\022\025.ser" +
      "vices.DemoMessage\032\025.services.DemoMessage" +
      "\"\000B \n\020org.example.grpcB\nDemoProtosP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_services_DemoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_DemoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_DemoMessage_descriptor,
        new java.lang.String[] { "Field1", "Field9", "Field18", "Field80", "Field81", "Field2", "Field3", "Field280", "Field6", "Field22", "Field4", "Field5", "Field59", "Field7", "Field16", "Field130", "Field12", "Field17", "Field13", "Field14", "Field104", "Field100", "Field101", "Field102", "Field103", "Field29", "Field30", "Field60", "Field271", "Field272", "Field150", "Field23", "Field24", "Field25", "Field78", "Field67", "Field68", "Field128", "Field129", "Field131", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
