// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

// Protobuf Java Version: 3.25.3
package org.example.grpc;

public interface HelloMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.HelloMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
