// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package org.example.grpc;

public interface HelloMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.HelloMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
